import { formatDate, formatTime } from '../../utils/format';

export type TimelineReportRow = {
  id: number; event_time: string; created_at: string; event_type: string; location_name: string;
  full_address?: string | null; site?: { name?: string; address?: string } | null; latitude?: number | null;
  longitude?: number | null; accuracy?: number | null; attendance_id?: number | null;
  employee?: { first_name?: string; last_name?: string; employee_code?: string } | null;
};

export type TimelineReportMeta = { employeeName: string; reportType: 'Daily' | 'Weekly' | 'Monthly'; dateRange: string; generatedOn: string; generatedBy: string; };

const eventLabel = (value: string) => value.split('_').map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(' ');
const employeeName = (row: TimelineReportRow) => [row.employee?.first_name, row.employee?.last_name].filter(Boolean).join(' ');
const value = (row: TimelineReportRow, key: string) => {
  const values: Record<string, string> = {
    Date: formatDate(row.event_time), Time: formatTime(row.event_time), 'Employee Name': employeeName(row),
    'Employee Code': row.employee?.employee_code || '', 'Event Type': eventLabel(row.event_type),
    'Location Name': row.location_name || '', 'Full Address': row.full_address || row.site?.address || '',
    'Site Name': row.site?.name || '', Latitude: row.latitude == null ? '' : String(row.latitude),
    Longitude: row.longitude == null ? '' : String(row.longitude), Accuracy: row.accuracy == null ? '' : String(row.accuracy),
    'Attendance ID': row.attendance_id == null ? '' : String(row.attendance_id),
    'Checkout Type': row.event_type === 'auto_checkout' ? 'Auto Checkout' : row.event_type === 'check_out' ? 'Manual Checkout' : '',
    'Created At': row.created_at || '',
  };
  return values[key] || '';
};
const headers = ['Date', 'Time', 'Employee Name', 'Employee Code', 'Event Type', 'Location Name', 'Full Address', 'Site Name', 'Latitude', 'Longitude', 'Accuracy', 'Attendance ID', 'Checkout Type', 'Created At'];
const csvEscape = (text: string) => `"${text.replace(/"/g, '""')}"`;

export function buildTimelineReportCsv(rows: TimelineReportRow[]) {
  return [headers.join(','), ...rows.map((row) => headers.map((header) => csvEscape(value(row, header))).join(','))].join('\n');
}

const pdfEscape = (text: string) => text.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
const text = (value: string, x: number, y: number, size = 8, bold = false) => `BT /${bold ? 'F2' : 'F1'} ${size} Tf ${x} ${y} Td (${pdfEscape(value)}) Tj ET\n`;
const wrap = (input: string, width: number) => {
  const maximum = Math.max(8, Math.floor(width / 4.1)); const words = input.split(/\s+/); const lines: string[] = []; let line = '';
  words.forEach((word) => { const next = line ? `${line} ${word}` : word; if (next.length > maximum && line) { lines.push(line); line = word; } else line = next; });
  if (line) lines.push(line); return lines.length ? lines : [''];
};

export function buildTimelineReportPdf(rows: TimelineReportRow[], meta: TimelineReportMeta) {
  const pageWidth = 792, pageHeight = 612, margin = 18, lineHeight = 10, tableTop = 494, bottom = 28;
  const columns = headers.slice(0, -1); const width = (pageWidth - margin * 2) / columns.length;
  const pages: TimelineReportRow[][] = []; let page: TimelineReportRow[] = []; let used = tableTop - 22;
  rows.forEach((row) => { const lines = Math.max(...columns.map((header) => wrap(value(row, header), width - 4).length)); const height = Math.max(18, lines * lineHeight + 6); if (used - height < bottom && page.length) { pages.push(page); page = []; used = tableTop - 22; } page.push(row); used -= height; }); pages.push(page);
  const streams = pages.map((pageRows, index) => {
    let out = text('AIHP CrewTrack', margin, 582, 16, true) + text('Employee Location Timeline', margin, 562, 13, true);
    out += text(`Employee: ${meta.employeeName}`, margin, 546) + text(`Report Type: ${meta.reportType}`, margin, 534) + text(`Date Range: ${meta.dateRange}`, margin, 522) + text(`Generated On: ${meta.generatedOn}`, margin, 510) + text(`Generated By: ${meta.generatedBy}`, 320, 510);
    let x = margin; columns.forEach((header) => { out += text(header, x + 2, tableTop, 6, true); x += width; }); let y = tableTop - 12;
    pageRows.forEach((row) => { const cells = columns.map((header) => wrap(value(row, header), width - 4)); const lines = Math.max(...cells.map((cell) => cell.length)); const height = Math.max(18, lines * lineHeight + 6); x = margin; cells.forEach((cell) => { cell.forEach((line, lineIndex) => { out += text(line, x + 2, y - 8 - lineIndex * lineHeight, 6); }); x += width; }); out += `0.5 w ${margin} ${y - height} m ${pageWidth - margin} ${y - height} l S\n`; y -= height; });
    out += text(`Page ${index + 1} of ${pages.length}`, pageWidth - 86, 14, 8); return out;
  });
  const objects: string[] = ['1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj', `2 0 obj << /Type /Pages /Kids [${streams.map((_, i) => `${3 + i * 2} 0 R`).join(' ')}] /Count ${streams.length} >> endobj`];
  streams.forEach((stream, index) => { const pageObject = 3 + index * 2, streamObject = pageObject + 1, font1 = 3 + streams.length * 2, font2 = font1 + 1; objects.push(`${pageObject} 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /Font << /F1 ${font1} 0 R /F2 ${font2} 0 R >> >> /Contents ${streamObject} 0 R >> endobj`); objects.push(`${streamObject} 0 obj << /Length ${stream.length} >> stream\n${stream}\nendstream endobj`); });
  objects.push(`${3 + streams.length * 2} 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj`, `${4 + streams.length * 2} 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >> endobj`);
  let pdf = '%PDF-1.4\n'; const offsets = [0]; objects.forEach((object) => { offsets.push(pdf.length); pdf += object + '\n'; }); const xref = pdf.length; pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`; offsets.slice(1).forEach((offset) => { pdf += `${String(offset).padStart(10, '0')} 00000 n \n`; }); return pdf + `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
}

