import React, { useMemo, useState } from 'react';
import { Alert, Platform, ScrollView, StyleSheet, View } from 'react-native';
import { Button, Card, Menu, Text, TextInput, useTheme } from 'react-native-paper';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useQuery } from '@tanstack/react-query';
import { useAuth } from '../../hooks/useAuth';
import { adminApi } from '../../services/api';
import { getLocationTimeline } from '../../services/locationTimelineService';
import { savePlatformReportFile } from '../../services/reportDownloader';
import { buildTimelineReportCsv, buildTimelineReportPdf, TimelineReportRow } from '../../services/reports/timelineExportBuilders';
import { formatDate, formatDateTime } from '../../utils/format';

type Period = 'daily' | 'weekly' | 'monthly';
const dateString = (date: Date) => date.toISOString().slice(0, 10);
function rangeFor(period: Period, value: string) { const start = new Date(`${value}T00:00:00`); if (period === 'weekly') start.setDate(start.getDate() - ((start.getDay() + 6) % 7)); if (period === 'monthly') start.setDate(1); const end = new Date(start); if (period === 'daily') end.setDate(end.getDate() + 1); else if (period === 'weekly') end.setDate(end.getDate() + 7); else end.setMonth(end.getMonth() + 1); return { start, end, from: start.toISOString(), to: end.toISOString() }; }
function weekToken(date: Date) { const copy = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate())); copy.setUTCDate(copy.getUTCDate() + 4 - (copy.getUTCDay() || 7)); const year = copy.getUTCFullYear(); const first = new Date(Date.UTC(year, 0, 1)); return `${year}-W${String(Math.ceil((((copy.getTime() - first.getTime()) / 86400000) + 1) / 7)).padStart(2, '0')}`; }
const safeName = (value: string) => value.replace(/[^a-z0-9]+/gi, '_').replace(/^_|_$/g, '');

export const TimelineReportsScreen: React.FC = () => {
  const theme = useTheme(); const { currentUser } = useAuth(); const today = useMemo(() => dateString(new Date()), []);
  const [employeeId, setEmployeeId] = useState<number | null>(null); const [period, setPeriod] = useState<Period>('daily'); const [date, setDate] = useState(today); const [employeesOpen, setEmployeesOpen] = useState(false); const [periodOpen, setPeriodOpen] = useState(false);
  const employees = useQuery({ queryKey: ['admin', 'timeline-report-employees', currentUser?.id], queryFn: async () => { const result = await adminApi.getEmployees(currentUser!.id); return result.success ? result.data || [] : []; }, enabled: !!currentUser?.id, staleTime: 300000 });
  const selected = (employees.data || []).find((row: any) => row.id === employeeId); const range = useMemo(() => rangeFor(period, date), [period, date]);
  const events = useQuery({ queryKey: ['admin', 'timeline-report', employeeId, range.from, range.to], queryFn: () => getLocationTimeline(employeeId!, range.from, range.to) as Promise<TimelineReportRow[]>, enabled: !!employeeId && /^\d{4}-\d{2}-\d{2}$/.test(date) });
  const exportReport = async (format: 'pdf' | 'csv') => { if (!selected) return Alert.alert('Select employee', 'Choose an employee first.'); const rows = events.data || []; if (!rows.length) return Alert.alert('No timeline records', 'There are no actual timeline records for this period.'); const employeeName = `${selected.first_name} ${selected.last_name}`.trim(); const token = period === 'daily' ? date : period === 'weekly' ? weekToken(range.start) : date.slice(0, 7); const filename = `EmployeeTimeline_${safeName(employeeName)}_${token}.${format}`; const meta = { employeeName, reportType: (period.charAt(0).toUpperCase() + period.slice(1)) as 'Daily' | 'Weekly' | 'Monthly', dateRange: `${formatDate(range.start)} - ${formatDate(new Date(range.end.getTime() - 1))}`, generatedOn: formatDateTime(new Date()), generatedBy: currentUser?.name || currentUser?.email || 'Admin User' }; try { await savePlatformReportFile(filename, format === 'pdf' ? buildTimelineReportPdf(rows, meta) : buildTimelineReportCsv(rows), format === 'pdf' ? 'application/pdf' : 'text/csv'); Alert.alert('Download complete', Platform.OS === 'web' ? 'The browser download has started.' : filename); } catch (error: any) { Alert.alert('Download failed', error.message || 'Could not create the report.'); } };
  return <SafeAreaView style={[styles.container, { backgroundColor: theme.colors.background }]}><ScrollView contentContainerStyle={styles.content}><Card><Card.Content><Text variant="headlineSmall">Employee Location Timeline Reports</Text><Text variant="bodyMedium" style={styles.help}>Exports only the selected employee's real historical timeline records.</Text><Menu visible={employeesOpen} onDismiss={() => setEmployeesOpen(false)} anchor={<Button mode="outlined" onPress={() => setEmployeesOpen(true)} style={styles.field}>{selected ? `${selected.first_name} ${selected.last_name}` : 'Select employee'}</Button>}>{(employees.data || []).map((item: any) => <Menu.Item key={item.id} title={`${item.first_name} ${item.last_name}`} onPress={() => { setEmployeeId(item.id); setEmployeesOpen(false); }} />)}</Menu><Menu visible={periodOpen} onDismiss={() => setPeriodOpen(false)} anchor={<Button mode="outlined" onPress={() => setPeriodOpen(true)} style={styles.field}>{period.charAt(0).toUpperCase() + period.slice(1)}</Button>}>{(['daily','weekly','monthly'] as Period[]).map((item) => <Menu.Item key={item} title={item.charAt(0).toUpperCase() + item.slice(1)} onPress={() => { setPeriod(item); setPeriodOpen(false); }} />)}</Menu><TextInput mode="outlined" label={period === 'monthly' ? 'Any date in month (YYYY-MM-DD)' : period === 'weekly' ? 'Any date in week (YYYY-MM-DD)' : 'Date (YYYY-MM-DD)'} value={date} onChangeText={setDate} style={styles.field}/><View style={styles.actions}><Button mode="contained" onPress={() => exportReport('pdf')} disabled={!selected || events.isLoading}>Download PDF</Button><Button mode="outlined" onPress={() => exportReport('csv')} disabled={!selected || events.isLoading}>Download CSV</Button></View><Text variant="bodySmall" style={styles.help}>{events.isLoading ? 'Loading timeline records...' : selected ? `${(events.data || []).length} actual event(s) in selected period.` : 'Select an employee and period.'}</Text></Card.Content></Card></ScrollView></SafeAreaView>;
};
const styles = StyleSheet.create({ container: { flex: 1 }, content: { padding: 16 }, help: { marginVertical: 10, opacity: 0.7 }, field: { marginBottom: 12 }, actions: { gap: 10 } });

