do $$
begin
  create extension if not exists pg_cron;
exception
  when others then null;
end $$;

do $$
begin
  create extension if not exists pg_net;
exception
  when others then null;
end $$;

create table if not exists notification_delivery_logs (
  id bigint generated by default as identity primary key,
  channel text not null,
  recipient_type text not null check (recipient_type in ('admin', 'employee')),
  recipient_id bigint,
  notification_type text,
  title text,
  message text,
  token_count integer not null default 0,
  provider_request_id bigint,
  status text not null,
  details jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_notification_delivery_logs_channel_created_at
  on notification_delivery_logs(channel, created_at desc);

create or replace function public.queue_admin_push_notification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  payload jsonb := '[]'::jsonb;
  token_count integer := 0;
  request_id bigint;
begin
  if new.admin_id is null then
    return new;
  end if;

  select
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'to', nt.token,
          'title', new.title,
          'body', new.message,
          'sound', 'default',
          'channelId',
            case
              when new.type = 'alert' or coalesce(new.metadata->>'event', '') = 'auto_checkout' then 'alerts'
              else 'default'
            end,
          'data', jsonb_build_object(
            'notificationId', new.id,
            'adminId', new.admin_id,
            'type', new.type,
            'screen', 'Notifications',
            'metadata', coalesce(new.metadata, '{}'::jsonb)
          )
        )
      ),
      '[]'::jsonb
    ),
    count(*)
  into payload, token_count
  from notification_tokens nt
  where nt.admin_id = new.admin_id
    and nt.is_active = true;

  if token_count = 0 then
    insert into notification_delivery_logs (
      channel,
      recipient_type,
      recipient_id,
      notification_type,
      title,
      message,
      token_count,
      status,
      details
    ) values (
      'admin_push',
      'admin',
      new.admin_id,
      new.type,
      new.title,
      new.message,
      0,
      'skipped',
      jsonb_build_object(
        'reason', 'no_active_tokens',
        'notification_id', new.id,
        'metadata', coalesce(new.metadata, '{}'::jsonb)
      )
    );

    return new;
  end if;

  request_id := net.http_post(
    url := 'https://exp.host/--/api/v2/push/send',
    headers := '{"Content-Type":"application/json","Accept":"application/json"}'::jsonb,
    body := payload
  );

  insert into notification_delivery_logs (
    channel,
    recipient_type,
    recipient_id,
    notification_type,
    title,
    message,
    token_count,
    provider_request_id,
    status,
    details
  ) values (
    'admin_push',
    'admin',
    new.admin_id,
    new.type,
    new.title,
    new.message,
    token_count,
    request_id,
    'queued',
    jsonb_build_object(
      'notification_id', new.id,
      'metadata', coalesce(new.metadata, '{}'::jsonb)
    )
  );

  update notification_tokens
  set
    last_sent_at = now(),
    last_error = null,
    updated_at = now()
  where admin_id = new.admin_id
    and is_active = true;

  return new;
exception
  when others then
    insert into notification_delivery_logs (
      channel,
      recipient_type,
      recipient_id,
      notification_type,
      title,
      message,
      token_count,
      status,
      details
    ) values (
      'admin_push',
      'admin',
      new.admin_id,
      new.type,
      new.title,
      new.message,
      token_count,
      'error',
      jsonb_build_object(
        'notification_id', new.id,
        'error', sqlerrm,
        'metadata', coalesce(new.metadata, '{}'::jsonb)
      )
    );

    update notification_tokens
    set
      last_error = sqlerrm,
      updated_at = now()
    where admin_id = new.admin_id
      and is_active = true;

    return new;
end;
$$;

create or replace function public.send_daily_checkin_reminders(reference_time timestamptz default now())
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  reminder_date date := (reference_time at time zone 'Asia/Kolkata')::date;
  payload jsonb := '[]'::jsonb;
  token_count integer := 0;
  employee_ids bigint[];
  request_id bigint;
begin
  with targets as (
    select distinct
      e.id as employee_id,
      nt.token
    from employees e
    join notification_tokens nt
      on nt.employee_id = e.id
     and nt.is_active = true
    where e.is_active = true
      and not exists (
        select 1
        from attendance a
        where a.employee_id = e.id
          and ((a.check_in_time at time zone 'UTC') at time zone 'Asia/Kolkata')::date = reminder_date
      )
  )
  select
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'to', token,
          'title', 'Attendance Reminder',
          'body', 'Please check in today.',
          'sound', 'default',
          'channelId', 'attendance-reminders',
          'data', jsonb_build_object(
            'type', 'system',
            'notificationKind', 'daily_checkin_reminder',
            'reminderDate', reminder_date::text
          )
        )
      ),
      '[]'::jsonb
    ),
    count(*),
    coalesce(array_agg(employee_id), '{}'::bigint[])
  into payload, token_count, employee_ids
  from targets;

  if token_count = 0 then
    insert into notification_delivery_logs (
      channel,
      recipient_type,
      notification_type,
      title,
      message,
      token_count,
      status,
      details
    ) values (
      'employee_checkin_reminder',
      'employee',
      'system',
      'Attendance Reminder',
      'Please check in today.',
      0,
      'skipped',
      jsonb_build_object(
        'reason', 'no_eligible_tokens',
        'reminder_date', reminder_date::text
      )
    );

    return 0;
  end if;

  request_id := net.http_post(
    url := 'https://exp.host/--/api/v2/push/send',
    headers := '{"Content-Type":"application/json","Accept":"application/json"}'::jsonb,
    body := payload
  );

  insert into notification_delivery_logs (
    channel,
    recipient_type,
    notification_type,
    title,
    message,
    token_count,
    provider_request_id,
    status,
    details
  ) values (
    'employee_checkin_reminder',
    'employee',
    'system',
    'Attendance Reminder',
    'Please check in today.',
    token_count,
    request_id,
    'queued',
    jsonb_build_object(
      'reminder_date', reminder_date::text,
      'employee_ids', to_jsonb(employee_ids)
    )
  );

  update notification_tokens
  set
    last_sent_at = now(),
    last_error = null,
    updated_at = now()
  where employee_id = any(employee_ids)
    and is_active = true;

  return token_count;
exception
  when others then
    insert into notification_delivery_logs (
      channel,
      recipient_type,
      notification_type,
      title,
      message,
      token_count,
      status,
      details
    ) values (
      'employee_checkin_reminder',
      'employee',
      'system',
      'Attendance Reminder',
      'Please check in today.',
      token_count,
      'error',
      jsonb_build_object(
        'reminder_date', reminder_date::text,
        'error', sqlerrm
      )
    );

    return 0;
end;
$$;

grant execute on function public.send_daily_checkin_reminders(timestamptz) to anon, authenticated;

do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    if exists (select 1 from cron.job where jobname = 'daily-checkin-reminder') then
      perform cron.unschedule('daily-checkin-reminder');
    end if;

    perform cron.schedule(
      'daily-checkin-reminder',
      '0 4 * * *',
      'select public.send_daily_checkin_reminders(now());'
    );
  end if;
exception
  when others then null;
end $$;
