-- Additive, forward-only historical timeline. No existing records are modified.
create table if not exists public.location_timeline (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on delete restrict,
  attendance_id bigint references public.attendance(id) on delete set null,
  event_time timestamptz not null,
  latitude double precision,
  longitude double precision,
  location_name text not null default 'Unknown location',
  full_address text,
  site_id bigint references public.work_sites(id) on delete set null,
  event_type text not null check (event_type in ('check_in','location_update','site_arrival','site_departure','unknown_location','movement','check_out','auto_checkout')),
  accuracy double precision,
  idempotency_key text,
  created_at timestamptz not null default now()
);

-- Compatibility for databases where the earlier table-only draft was run first.
-- These changes affect only the new timeline table; no application data is touched.
alter table public.location_timeline add column if not exists full_address text;
alter table public.location_timeline add column if not exists idempotency_key text;
create unique index if not exists location_timeline_idempotency_key_idx
  on public.location_timeline (idempotency_key);

create index if not exists location_timeline_employee_event_time_idx on public.location_timeline (employee_id, event_time);
create index if not exists location_timeline_attendance_event_time_idx on public.location_timeline (attendance_id, event_time);

alter table public.location_timeline enable row level security;

create policy "employees insert their own location timeline" on public.location_timeline for insert to authenticated
  with check (exists (select 1 from public.employees e where e.id = public.location_timeline.employee_id and e.auth_user_id = auth.uid()));
create policy "employees read their own location timeline" on public.location_timeline for select to authenticated
  using (exists (select 1 from public.employees e where e.id = public.location_timeline.employee_id and e.auth_user_id = auth.uid()));
create policy "admins read their employee timelines" on public.location_timeline for select to authenticated
  using (exists (select 1 from public.employees e join public.admins a on a.id = e.admin_id where e.id = public.location_timeline.employee_id and a.auth_user_id = auth.uid()));

-- A fail-safe observer: it never changes attendance/live location and swallows all errors.
create or replace function public.capture_auto_checkout_timeline_event()
returns trigger language plpgsql security definer set search_path = public as $$
declare latest_location record;
begin
  if new.checkout_type = 'auto_checkout' and old.check_out_time is null and new.check_out_time is not null then
    begin
      select latitude, longitude, location_name into latest_location
      from public.location_tracking where employee_id = new.employee_id order by timestamp desc nulls last limit 1;
      insert into public.location_timeline (employee_id, attendance_id, event_time, latitude, longitude, location_name, site_id, event_type, idempotency_key)
      values (new.employee_id, new.id, new.check_out_time, latest_location.latitude, latest_location.longitude,
        coalesce(latest_location.location_name, 'Unknown (employee offline)'), null, 'auto_checkout', 'auto-checkout:' || new.id::text)
      on conflict (idempotency_key) do nothing;
    exception when others then null;
    end;
  end if;
  return new;
end $$;

drop trigger if exists location_timeline_after_auto_checkout on public.attendance;
create trigger location_timeline_after_auto_checkout after update of check_out_time, checkout_type on public.attendance
  for each row execute function public.capture_auto_checkout_timeline_event();

-- Read-only monitoring:
-- select count(*) total_rows, pg_size_pretty(pg_total_relation_size('public.location_timeline')) total_size from public.location_timeline;
-- select employee_id, count(*) rows from public.location_timeline group by employee_id order by rows desc;
-- select employee_id, event_time::date day, count(*) rows from public.location_timeline group by 1,2 order by 2 desc;
-- select event_time::date day, count(*) events from public.location_timeline group by 1 order by 1 desc;

