do $$
begin
  create extension if not exists pg_net;
exception
  when others then null;
end $$;

create table if not exists notification_tokens (
  id bigint generated by default as identity primary key,
  token text not null,
  platform text not null check (platform in ('android', 'ios')),
  admin_id bigint references admins(id) on delete cascade,
  employee_id bigint references employees(id) on delete cascade,
  is_active boolean not null default true,
  last_sent_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint notification_tokens_token_key unique (token),
  constraint notification_tokens_single_owner_chk check (
    (admin_id is not null and employee_id is null)
    or (admin_id is null and employee_id is not null)
  )
);

create index if not exists idx_notification_tokens_admin_id
  on notification_tokens(admin_id)
  where admin_id is not null;

create index if not exists idx_notification_tokens_employee_id
  on notification_tokens(employee_id)
  where employee_id is not null;

create index if not exists idx_notification_tokens_active_admin
  on notification_tokens(admin_id, is_active)
  where admin_id is not null;

alter table notification_tokens enable row level security;

create or replace function public.queue_admin_push_notification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  payload jsonb;
begin
  if new.admin_id is null then
    return new;
  end if;

  select jsonb_agg(
    jsonb_build_object(
      'to', nt.token,
      'title', new.title,
      'body', new.message,
      'sound', 'default',
      'channelId',
        case
          when new.type = 'alert' or coalesce(new.metadata->>'event', '') = 'auto_checkout' then 'alerts'
          else 'default'
        end,
      'data', jsonb_build_object(
        'notificationId', new.id,
        'adminId', new.admin_id,
        'type', new.type,
        'screen', 'Notifications',
        'metadata', coalesce(new.metadata, '{}'::jsonb)
      )
    )
  )
  into payload
  from notification_tokens nt
  where nt.admin_id = new.admin_id
    and nt.is_active = true;

  if payload is null then
    return new;
  end if;

  perform net.http_post(
    url := 'https://exp.host/--/api/v2/push/send',
    headers := '{"Content-Type":"application/json","Accept":"application/json"}'::jsonb,
    body := payload
  );

  update notification_tokens
  set
    last_sent_at = now(),
    last_error = null,
    updated_at = now()
  where admin_id = new.admin_id
    and is_active = true;

  return new;
exception
  when others then
    update notification_tokens
    set
      last_error = sqlerrm,
      updated_at = now()
    where admin_id = new.admin_id
      and is_active = true;

    return new;
end;
$$;

drop trigger if exists trg_queue_admin_push_notification on notifications;

create trigger trg_queue_admin_push_notification
after insert on notifications
for each row
execute function public.queue_admin_push_notification();
